### ISSUE TITLE
more than one number in string, or number plus other word won't parse

### ISSUE THREAD

**Issue by davebraze** [fsingletonthorn/words_to_numbers#6]
words_to_numbers was working well for me a few months ago (May). Then, after not using it for a while, I came back to the project where I used it and I am confronted with this issue:

A string with a single number word parses correctly:

R> library(wordstonumbers)
R> words_to_numbers("forty")
[1] "40"
R> words_to_numbers("three")
[1] "3"

But a string with more than one number word does not:

R> words_to_numbers("forty three")
Error: Assigned data `dplyr::select(numericsOnly, -"tochange")` must be compatible with existing data.
i Error occurred for column `group`.
x Can't convert <character> to <double>.
Run `rlang::last_error()` to see where the error occurred.
R> words_to_numbers("forty-three")
Error: Assigned data `dplyr::select(numericsOnly, -"tochange")` must be compatible with existing data.
i Error occurred for column `group`.
x Can't convert <character> to <double>.
Run `rlang::last_error()` to see where the error occurred.

Nor does a string with a number word and other text:

R> words_to_numbers("three cats")
Error: Assigned data `dplyr::select(numericsOnly, -"tochange")` must be compatible with existing data.
i Error occurred for column `group`.
x Can't convert <character> to <double>.
Run `rlang::last_error()` to see where the error occurred.

Previously (when things worked) I was using R 3.6.1 64 bit on Windows and wordstonumbers 1.0.0

The present problem occurs on that version of R as well as R 4.0.3 64 bit on Windows

It's possible/likely that I've update my version of dplyr in the interim (see error message above), but I'm not sure which dplyr I was using previously.

Here's sessionInfo() for the session that generated the output above:

R> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] wordstonumbers_1.0.0 usethis_1.6.3       

loaded via a namespace (and not attached):
 [1] magrittr_1.5     tidyselect_1.1.0 R6_2.5.0         rlang_0.4.8      stringr_1.4.0   
 [6] dplyr_1.0.2      tools_4.0.3      ellipsis_0.3.1   tibble_3.0.4     lifecycle_0.2.0 
[11] crayon_1.3.4     purrr_0.3.4      tidyr_1.1.2      vctrs_0.3.4      fs_1.5.0        
[16] glue_1.4.2       stringi_1.5.3    compiler_4.0.3   pillar_1.4.6     generics_0.1.0  
[21] pkgconfig_2.0.3 

Is this a known problem? Any recommendations?

**Comment by fsingletonthorn** [comment]
Looks like a subset of a numeric vector was being updated with a character vector, which used to just implicitly coerce the whole column to character, but now causes errors apparently. I've patched it up now with ae9ba5b, and version 1.0.1 should work again. Thanks for the comprehensive bug report - made it very easy to fix.

**Comment by davebraze** [comment]
That's fantastic. Thank you! 

One minor point wrt your readme for the package: install_github() has been moved from the 'devtools' to 'remotes'. 

In case you're interested, I'm using wordstonumbers here: https://github.com/davebraze/ct-covid19 (https://davebraze.github.io/ct-covid19/). I may update that soon, thanks to your help.

**Comment by fsingletonthorn** [comment]
Thanks - fixed that too! Nice to see it being put to good use.
